server:
  port: 9090

spring :
  datasource :
    url : jdbc:h2:tcp://localhost/~/test
    driver-class-name : org.h2.Driver
    username : sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    org.springframework: debug
    org.springframework.security: info
    org.hibernate: trace
    org:
      hibernate:
        type: trace